# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import InventorySystem_pb2 as InventorySystem__pb2


class InventorySystemStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getStock = channel.unary_stream(
        '/InventorySystem/getStock',
        request_serializer=InventorySystem__pb2.Empty.SerializeToString,
        response_deserializer=InventorySystem__pb2.Product.FromString,
        )
    self.createOrder = channel.unary_unary(
        '/InventorySystem/createOrder',
        request_serializer=InventorySystem__pb2.Order.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.getOrder = channel.unary_unary(
        '/InventorySystem/getOrder',
        request_serializer=InventorySystem__pb2.orderID.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderAddProducts = channel.unary_unary(
        '/InventorySystem/updateOrderAddProducts',
        request_serializer=InventorySystem__pb2.AddProducts.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderRemoveProducts = channel.unary_unary(
        '/InventorySystem/updateOrderRemoveProducts',
        request_serializer=InventorySystem__pb2.RemoveProducts.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderChangeDestination = channel.unary_unary(
        '/InventorySystem/updateOrderChangeDestination',
        request_serializer=InventorySystem__pb2.ChangeDestination.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderChangeDate = channel.unary_unary(
        '/InventorySystem/updateOrderChangeDate',
        request_serializer=InventorySystem__pb2.ChangeDate.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderIsShipped = channel.unary_unary(
        '/InventorySystem/updateOrderIsShipped',
        request_serializer=InventorySystem__pb2.IsShipped.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )
    self.updateOrderIsPaid = channel.unary_unary(
        '/InventorySystem/updateOrderIsPaid',
        request_serializer=InventorySystem__pb2.IsPaid.SerializeToString,
        response_deserializer=InventorySystem__pb2.Order.FromString,
        )


class InventorySystemServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getStock(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderAddProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderRemoveProducts(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderChangeDestination(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderChangeDate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderIsShipped(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def updateOrderIsPaid(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_InventorySystemServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getStock': grpc.unary_stream_rpc_method_handler(
          servicer.getStock,
          request_deserializer=InventorySystem__pb2.Empty.FromString,
          response_serializer=InventorySystem__pb2.Product.SerializeToString,
      ),
      'createOrder': grpc.unary_unary_rpc_method_handler(
          servicer.createOrder,
          request_deserializer=InventorySystem__pb2.Order.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'getOrder': grpc.unary_unary_rpc_method_handler(
          servicer.getOrder,
          request_deserializer=InventorySystem__pb2.orderID.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderAddProducts': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderAddProducts,
          request_deserializer=InventorySystem__pb2.AddProducts.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderRemoveProducts': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderRemoveProducts,
          request_deserializer=InventorySystem__pb2.RemoveProducts.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderChangeDestination': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderChangeDestination,
          request_deserializer=InventorySystem__pb2.ChangeDestination.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderChangeDate': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderChangeDate,
          request_deserializer=InventorySystem__pb2.ChangeDate.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderIsShipped': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderIsShipped,
          request_deserializer=InventorySystem__pb2.IsShipped.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
      'updateOrderIsPaid': grpc.unary_unary_rpc_method_handler(
          servicer.updateOrderIsPaid,
          request_deserializer=InventorySystem__pb2.IsPaid.FromString,
          response_serializer=InventorySystem__pb2.Order.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'InventorySystem', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
